!Copyright>        OpenRadioss
!Copyright>        Copyright (C) 1986-2025 Altair Engineering Inc.
!Copyright>
!Copyright>        This program is free software: you can redistribute it and/or modify
!Copyright>        it under the terms of the GNU Affero General Public License as published by
!Copyright>        the Free Software Foundation, either version 3 of the License, or
!Copyright>        (at your option) any later version.
!Copyright>
!Copyright>        This program is distributed in the hope that it will be useful,
!Copyright>        but WITHOUT ANY WARRANTY; without even the implied warranty of
!Copyright>        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!Copyright>        GNU Affero General Public License for more details.
!Copyright>
!Copyright>        You should have received a copy of the GNU Affero General Public License
!Copyright>        along with this program.  If not, see <https://www.gnu.org/licenses/>.
!Copyright>
!Copyright>
!Copyright>        Commercial Alternative: Altair Radioss Software
!Copyright>
!Copyright>        As an alternative to this open-source version, Altair also offers Altair Radioss
!Copyright>        software under a commercial license.  Contact Altair to discuss further if the
!Copyright>        commercial version may interest you: https://www.altair.com/radioss/.
!||====================================================================
!||    element_mod                         ../common_source/modules/elements/element_mod.F90
!||--- called by ------------------------------------------------------
!||    admbcs                              ../starter/source/model/remesh/admbcs.F
!||    admbcs3                             ../starter/source/model/remesh/admbcs.F
!||    admbcs4                             ../starter/source/model/remesh/admbcs.F
!||    agrad2                              ../engine/source/ale/ale2d/agrad2.F
!||    agrad3                              ../engine/source/ale/ale3d/agrad3.F
!||    ale_check_lag                       ../starter/source/ale/ale_check_lag.F
!||    ale_element_size_computation        ../starter/source/initial_conditions/inivol/ale_element_size_computation.F
!||    alelec                              ../starter/source/ale/alelec.F
!||    aleso2                              ../starter/source/ale/ale2d/aleso2.F
!||    aleso2t                             ../starter/source/ale/ale2d/aleso2t.F
!||    aleso3                              ../starter/source/ale/ale3d/aleso3.F
!||    allocxfem                           ../starter/source/elements/xfem/allocxfem.F
!||    ani_fasolfr1                        ../starter/source/output/anim/ani_fasolfr.F
!||    ani_segquadfr1                      ../starter/source/output/anim/ani_segquadfr.F
!||    aniskew                             ../engine/source/output/anim/generate/aniskew.F
!||    aniskewf                            ../engine/source/output/anim/generate/aniskewf.F
!||    aturi3                              ../starter/source/ale/ale3d/aturi3.F
!||    bimat2                              ../starter/source/ale/bimat/bimat2.F
!||    binit2                              ../starter/source/ale/bimat/binit2.F
!||    bsigini                             ../starter/source/elements/beam/bsigini.F
!||    build_admesh                        ../starter/source/model/remesh/build_admesh.F
!||    build_cnel                          ../starter/source/model/mesh/build_cnel.F
!||    buserini                            ../starter/source/elements/beam/buserini.F
!||    c3coori                             ../starter/source/elements/sh3n/coque3n/c3coori.F
!||    c3derii                             ../starter/source/elements/sh3n/coque3n/c3derii.F
!||    c3eps11_ini                         ../starter/source/elements/sh3n/coque3n/c3init3.F
!||    c3epschk                            ../starter/source/elements/sh3n/coque3n/c3init3.F
!||    c3epsini                            ../starter/source/elements/sh3n/coque3n/c3epsini.F
!||    c3fint_reg_ini                      ../starter/source/elements/sh3n/coque3n/c3fint_reg_ini.F
!||    c3grhead                            ../starter/source/elements/sh3n/coque3n/c3grhead.F
!||    c3grtails                           ../starter/source/elements/sh3n/coque3n/c3grtails.F
!||    c3init3                             ../starter/source/elements/sh3n/coque3n/c3init3.F
!||    c3inmas                             ../starter/source/elements/sh3n/coque3n/c3inmas.F
!||    c_fvbag                             ../starter/source/airbag/c_fvbag.F
!||    c_idglob                            ../starter/source/restart/ddsplit/c_idglob.F
!||    c_iebcs                             ../starter/source/restart/ddsplit/c_iebcs.F
!||    c_ixfloc                            ../starter/source/restart/ddsplit/c_ixfloc.F
!||    c_ncrkxfem                          ../starter/source/restart/ddsplit/c_ncrkxfem.F
!||    c_vois                              ../starter/source/restart/ddsplit/c_vois.F
!||    cbafint_reg_ini                     ../starter/source/elements/shell/coqueba/cbafint_reg_ini.F
!||    cbainit3                            ../starter/source/elements/shell/coqueba/cbainit3.F
!||    ccoori                              ../starter/source/elements/shell/coque/ccoori.F
!||    cdk6inx                             ../starter/source/elements/sh3n/coquedk6/cdk6inx.F
!||    cdkderii                            ../starter/source/elements/sh3n/coquedk/cdkderii.F
!||    cdkepsini                           ../starter/source/elements/sh3n/coquedk/cdkepsini.F
!||    cdkfint_reg_ini                     ../starter/source/elements/sh3n/coquedk/cdkfint_reg_ini.F
!||    cdkinit3                            ../starter/source/elements/sh3n/coquedk/cdkinit3.F
!||    cdleni                              ../starter/source/elements/shell/coque/cdleni.F
!||    cepschk                             ../starter/source/elements/shell/coque/cepsini.F
!||    cepsini                             ../starter/source/elements/shell/coque/cepsini.F
!||    cfint_reg_ini                       ../starter/source/elements/shell/coque/cfint_reg_ini.F
!||    cgrhead                             ../starter/source/elements/shell/coque/cgrhead.F
!||    cgrtails                            ../starter/source/elements/shell/coque/cgrtails.F
!||    check_dynain                        ../starter/source/starter/check_dynain.F
!||    check_mat_elem_prop_compatibility   ../starter/source/materials/mat/check_mat_elem_prop_compatibility.F
!||    check_skew                          ../starter/source/spmd/domain_decomposition/check_skew.F
!||    checkvolume_4n                      ../starter/source/elements/solid/solide/checksvolume.F
!||    checkvolume_6n                      ../starter/source/elements/solid/solide/checksvolume.F
!||    checkvolume_8n                      ../starter/source/elements/solid/solide/checksvolume.F
!||    chk_dttsh                           ../starter/source/elements/thickshell/solidec/scdtchk3.F
!||    chk_flg_fsi                         ../starter/source/coupling/rad2rad/routines_r2r.F
!||    cinit3                              ../starter/source/elements/shell/coque/cinit3.F
!||    cinmas                              ../starter/source/elements/shell/coque/cinmas.F
!||    cndleni                             ../starter/source/elements/shell/coqueba/cndleni.F
!||    cnepsini                            ../starter/source/elements/shell/coqueba/cnepsini.F
!||    contrl                              ../starter/source/starter/contrl.F
!||    corthini                            ../starter/source/elements/shell/coque/corthini.F
!||    create_box_clause                   ../starter/source/model/sets/create_box_clause.F
!||    create_line_from_element            ../starter/source/model/sets/create_line_from_element.F
!||    create_map_tables                   ../starter/source/model/sets/map_tables.F
!||    create_node_from_element            ../starter/source/model/sets/create_node_from_element.F
!||    create_seatbelt                     ../starter/source/tools/seatbelts/create_seatbelt.F
!||    create_set_clause                   ../starter/source/model/sets/create_set_clause.F
!||    create_set_collect                  ../starter/source/model/sets/create_setcol_clause.F
!||    create_setcol_clause                ../starter/source/model/sets/create_setcol_clause.F
!||    create_surface_from_element         ../starter/source/model/sets/create_surface_from_element.F
!||    csms11_ini                          ../starter/source/elements/shell/coque/cinit3.F
!||    ddsplit                             ../starter/source/restart/ddsplit/ddsplit.F
!||    deallocate_elbuf                    ../starter/source/elements/elbuf_init/deallocate_buffer.F
!||    delnumbc                            ../engine/source/output/anim/generate/delnumbc.F
!||    delnumbf                            ../engine/source/output/anim/generate/delnumbf.F
!||    delnumbs                            ../engine/source/output/anim/generate/delnumb6.F
!||    desout                              ../starter/source/output/outp/desout.F
!||    dfuncc                              ../engine/source/output/anim/generate/dfuncc.F
!||    dfuncf                              ../engine/source/output/anim/generate/dfuncf.F
!||    dfuncs                              ../engine/source/output/anim/generate/dfunc6.F
!||    dmasanic                            ../engine/source/output/anim/generate/dmasanic.F
!||    dmasanif                            ../engine/source/output/anim/generate/dmasanif.F
!||    dmasanis                            ../engine/source/output/anim/generate/dmasani6.F
!||    domdec1                             ../starter/source/spmd/domain_decomposition/domdec1.F
!||    domdec2                             ../starter/source/spmd/domdec2.F
!||    dometis                             ../starter/source/spmd/domain_decomposition/grid2mat.F
!||    donesec                             ../engine/source/output/anim/generate/donesec.F
!||    dparrws                             ../engine/source/output/anim/generate/dparrws.F
!||    dsdim0                              ../starter/source/implicit/dsolve/dsdim.F
!||    dseccnt                             ../engine/source/output/anim/generate/dseccnt.F
!||    elbuf_ini                           ../engine/source/elements/elbuf/elbuf_ini.F
!||    elcut3n                             ../starter/source/elements/xfem/lslocal.F
!||    elcut4n                             ../starter/source/elements/xfem/lslocal.F
!||    elstagbox                           ../starter/source/model/box/bigbox.F
!||    elstagboxbox                        ../starter/source/model/box/boxbox.F
!||    eporin3                             ../starter/source/ale/ale3d/eporin3.F
!||    f_nodloc2                           ../starter/source/restart/ddsplit/f_nodloc2.F
!||    facebox                             ../starter/source/model/box/bigbox.F
!||    failwave_init                       ../starter/source/materials/fail/failwave_init.F
!||    father                              ../starter/source/model/remesh/build_admesh.F
!||    fillcne                             ../starter/source/spmd/domdec2.F
!||    fillcne_pxfem                       ../starter/source/properties/composite_options/stack/preplyxfem.F
!||    fillcne_xfem                        ../starter/source/elements/xfem/fillcne_xfem.F
!||    find_nodes                          ../starter/source/spmd/domain_decomposition/grid2mat.F
!||    fsigcini                            ../starter/source/constraints/fxbody/fsigcini.F
!||    fsigpini                            ../starter/source/constraints/fxbody/fsigpini.F
!||    fsigsini                            ../starter/source/constraints/fxbody/fsigsini.F
!||    fsigtini                            ../starter/source/constraints/fxbody/fsigtini.F
!||    fsigtrini                           ../starter/source/constraints/fxbody/fsigtrini.F
!||    fvbag_vertex                        ../starter/source/spmd/domain_decomposition/grid2mat.F
!||    fvbric0                             ../starter/source/airbag/fvbric0.F
!||    fvbric01                            ../starter/source/airbag/fvbric01.F
!||    fvbric1                             ../starter/source/airbag/fvbric1.F
!||    fvbric2                             ../starter/source/airbag/fvbric2.F
!||    fvelinte                            ../starter/source/airbag/fvelinte.F
!||    fvelprint                           ../starter/source/airbag/fvelprint.F
!||    fvelsurf                            ../starter/source/airbag/fvelsurf.F
!||    fvinjnormal                         ../starter/source/airbag/fvinjnormal.F
!||    fvmesh0                             ../engine/source/airbag/fvmesh0.F
!||    fvmesh1                             ../engine/source/airbag/fvmesh.F
!||    fxbelnum                            ../starter/source/constraints/fxbody/fxbelnum.F
!||    fxbsini                             ../starter/source/constraints/fxbody/fxbsini.F
!||    fxbtagn                             ../starter/source/constraints/fxbody/fxbtagn.F
!||    genani1                             ../starter/source/output/anim/genani1.F
!||    get_skew45                          ../starter/source/elements/joint/rjoint/rini45.F
!||    getphase                            ../starter/source/initial_conditions/inivol/getphase.F
!||    globvars                            ../starter/source/spmd/globvars.F
!||    hm_elngrr                           ../starter/source/groups/hm_elngrr.F
!||    hm_elngrs                           ../starter/source/groups/hm_elngr.F
!||    hm_lecgrn                           ../starter/source/groups/hm_lecgrn.F
!||    hm_prelce16s                        ../starter/source/elements/reader/hm_read_solid.F
!||    hm_read_beam                        ../starter/source/elements/reader/hm_read_beam.F
!||    hm_read_cluster                     ../starter/source/output/cluster/hm_read_cluster.F
!||    hm_read_convec                      ../starter/source/loads/thermic/hm_read_convec.F
!||    hm_read_drape                       ../starter/source/properties/composite_options/drape/hm_read_drape.F
!||    hm_read_eref                        ../starter/source/loads/reference_state/eref/hm_read_eref.F
!||    hm_read_gauge                       ../starter/source/output/gauge/hm_read_gauge.F
!||    hm_read_impflux                     ../starter/source/constraints/thermic/hm_read_impflux.F
!||    hm_read_impvel                      ../starter/source/constraints/general/impvel/hm_read_impvel.F
!||    hm_read_inistate_d00                ../starter/source/elements/initia/hm_read_inistate_d00.F
!||    hm_read_lines                       ../starter/source/groups/hm_read_lines.F
!||    hm_read_monvol_type1                ../starter/source/airbag/hm_read_monvol_type1.F
!||    hm_read_monvol_type10               ../starter/source/airbag/hm_read_monvol_type10.F
!||    hm_read_monvol_type11               ../starter/source/airbag/hm_read_monvol_type11.F
!||    hm_read_monvol_type2                ../starter/source/airbag/hm_read_monvol_type2.F
!||    hm_read_monvol_type3                ../starter/source/airbag/hm_read_monvol_type3.F
!||    hm_read_monvol_type4                ../starter/source/airbag/hm_read_monvol_type4.F
!||    hm_read_monvol_type5                ../starter/source/airbag/hm_read_monvol_type5.F
!||    hm_read_monvol_type6                ../starter/source/airbag/hm_read_monvol_type6.F
!||    hm_read_monvol_type7                ../starter/source/airbag/hm_read_monvol_type7.F
!||    hm_read_monvol_type8                ../starter/source/airbag/hm_read_monvol_type8.F
!||    hm_read_monvol_type9                ../starter/source/airbag/hm_read_monvol_type9.F
!||    hm_read_preload                     ../starter/source/loads/general/preload/hm_read_preload.F
!||    hm_read_quad                        ../starter/source/elements/reader/hm_read_quad.F
!||    hm_read_radiation                   ../starter/source/loads/thermic/hm_read_radiation.F
!||    hm_read_retractor                   ../starter/source/tools/seatbelts/hm_read_retractor.F
!||    hm_read_rwall_therm                 ../starter/source/constraints/general/rwall/hm_read_rwall_therm.F
!||    hm_read_sh3n                        ../starter/source/elements/reader/hm_read_sh3n.F
!||    hm_read_shell                       ../starter/source/elements/reader/hm_read_shell.F
!||    hm_read_slipring                    ../starter/source/tools/seatbelts/hm_read_slipring.F
!||    hm_read_solid                       ../starter/source/elements/reader/hm_read_solid.F
!||    hm_read_sphcel                      ../starter/source/elements/reader/hm_read_sphcel.F
!||    hm_read_spring                      ../starter/source/elements/reader/hm_read_spring.F
!||    hm_read_surf                        ../starter/source/groups/hm_read_surf.F
!||    hm_read_thgrou                      ../starter/source/output/th/hm_read_thgrou.F
!||    hm_read_tria                        ../starter/source/elements/reader/hm_read_tria.F
!||    hm_read_truss                       ../starter/source/elements/reader/hm_read_truss.F
!||    hm_read_xref                        ../starter/source/loads/reference_state/xref/hm_read_xref.F
!||    hm_set                              ../starter/source/model/sets/hm_set.F
!||    hm_setfxrbyon                       ../starter/source/constraints/fxbody/hm_setfxrbyon.F
!||    hm_yctrl                            ../starter/source/elements/initia/hm_yctrl.F
!||    i11coq                              ../starter/source/interfaces/inter3d1/i11coq.F
!||    i11fil                              ../starter/source/interfaces/inter3d1/i11coq.F
!||    i11sol                              ../starter/source/interfaces/inter3d1/i11sol.F
!||    i11sti3                             ../starter/source/interfaces/inter3d1/i11sti3.F
!||    i12chk3                             ../starter/source/interfaces/inter3d1/i12chk3.F
!||    i12sol3                             ../starter/source/interfaces/inter3d1/insol3.F
!||    i17sti3                             ../starter/source/interfaces/inter3d1/i17sti3.F
!||    i1chk3                              ../starter/source/interfaces/inter3d1/i1chk3.F
!||    i20ini3                             ../starter/source/interfaces/inter3d1/i20ini3.F
!||    i20nelts                            ../starter/source/interfaces/inter3d1/inelt.F
!||    i20sti3                             ../starter/source/interfaces/inter3d1/i20sti3.F
!||    i20sti3e                            ../starter/source/interfaces/inter3d1/i20sti3.F
!||    i21els3                             ../starter/source/interfaces/inter3d1/i21els3.F
!||    i21gap3                             ../engine/source/interfaces/int21/i21gap3.F
!||    i22err3                             ../starter/source/interfaces/inter3d1/i22err3.F
!||    i22tzinf                            ../starter/source/interfaces/inter3d1/i22tzinf.F
!||    i23gap3                             ../starter/source/interfaces/inter3d1/i23gap3.F
!||    i24gapm                             ../starter/source/interfaces/inter3d1/i24sti3.F
!||    i24ini_gap_n                        ../starter/source/interfaces/inter3d1/i24inisu_nei.F
!||    i24ll_kg                            ../starter/source/interfaces/inter3d1/i24sti3.F
!||    i24pen3                             ../engine/source/interfaces/intsort/i24pen3.F
!||    i24penmax                           ../starter/source/interfaces/inter3d1/i24pen3.F
!||    i24sti3                             ../starter/source/interfaces/inter3d1/i24sti3.F
!||    i24surfi                            ../starter/source/interfaces/inter3d1/i24surfi.F
!||    i24tri                              ../starter/source/interfaces/inter3d1/i24tri.F
!||    i25gapm                             ../starter/source/interfaces/inter3d1/i25sti3.F
!||    i25ini_gap_n                        ../starter/source/interfaces/inter3d1/i25neigh.F
!||    i25sti3                             ../starter/source/interfaces/inter3d1/i25sti3.F
!||    i25surfi                            ../starter/source/interfaces/inter3d1/i25surfi.F
!||    i2buc1                              ../starter/source/interfaces/inter3d1/i2buc1.F
!||    i2chk3                              ../starter/source/interfaces/inter3d1/i2chk3.F
!||    i2cor3                              ../starter/source/interfaces/inter3d1/i2cor3.F
!||    i2surfs                             ../starter/source/interfaces/inter3d1/i2surfs.F
!||    i2tid3                              ../starter/source/interfaces/inter3d1/i2tid3.F
!||    i2trivox                            ../starter/source/interfaces/inter3d1/i2trivox.F90
!||    i3sti3                              ../starter/source/interfaces/inter3d1/i3sti3.F
!||    i7sti3                              ../starter/source/interfaces/inter3d1/i7sti3.F
!||    i9sti3                              ../starter/source/interfaces/int09/i9sti3.F
!||    icinv3                              ../starter/source/interfaces/inter3d1/icinv3.F
!||    iconnet                             ../starter/source/interfaces/inter3d1/i24pen3.F
!||    identson3                           ../starter/source/model/remesh/build_admesh.F
!||    identson4                           ../starter/source/model/remesh/build_admesh.F
!||    iedge_xfem                          ../starter/source/elements/xfem/iedge_xfem.F
!||    in24coq_sol3                        ../starter/source/interfaces/inter3d1/i24surfi.F
!||    incoq3                              ../starter/source/interfaces/inter3d1/incoq3.F
!||    ind_s10edg                          ../starter/source/elements/solid/solide10/dim_s10edg.F
!||    ineltigeo                           ../starter/source/interfaces/inter3d1/inelt.F
!||    inelts                              ../starter/source/interfaces/inter3d1/inelt.F
!||    inelts_np                           ../starter/source/interfaces/inter3d1/i24sti3.F
!||    ingrbric                            ../starter/source/interfaces/interf1/ingrbric.F
!||    ingrbric_centroids                  ../starter/source/interfaces/interf1/ingrbric_centroids.F
!||    ingrbric_dx                         ../starter/source/interfaces/interf1/ingrbric_dx.F
!||    ingrbric_nodes                      ../starter/source/interfaces/interf1/ingrbric_nodes.F
!||    ini_inimap1d                        ../starter/source/initial_conditions/inimap/ini_inimap1d.F
!||    ini_inimap2d                        ../starter/stub/ini_inimap2d.F
!||    ini_seatbelt                        ../starter/source/tools/seatbelts/ini_seatbelt.F
!||    iniboltprel                         ../starter/source/loads/bolt/iniboltprel.F
!||    inicrkfill                          ../starter/source/elements/xfem/inicrkfill.F
!||    iniebcs                             ../starter/source/boundary_conditions/ebcs/iniebcs.F
!||    iniebcs_dp                          ../starter/source/boundary_conditions/ebcs/iniebcs_dp.F
!||    iniebcs_nrf_tcar                    ../starter/source/boundary_conditions/ebcs/iniebcs_nrf_tcar.F
!||    iniebcs_propellant                  ../starter/source/boundary_conditions/ebcs/iniebcs_propellant.F90
!||    iniebcs_propellant_get_cp           ../starter/source/boundary_conditions/ebcs/iniebcs_propellant.F90
!||    iniebcsp0                           ../starter/source/boundary_conditions/ebcs/iniebcsp0.F
!||    inifill                             ../starter/source/initial_conditions/inivol/inifill.F
!||    inigrav_load                        ../starter/source/initial_conditions/inigrav/inigrav_load.F
!||    inimom_fvm                          ../starter/source/elements/solid/solide/inimom_fvm.F
!||    inimu3                              ../starter/source/ale/bimat/inimu3.F
!||    inint3                              ../starter/source/interfaces/inter3d1/inint3.F
!||    inint3_thkvar                       ../starter/source/interfaces/inter3d1/inint3_thkvar.F
!||    inintr_orthdirfric                  ../starter/source/interfaces/interf1/inintr_orthdirfric.F
!||    iniphase                            ../starter/source/initial_conditions/inivol/iniphase.F
!||    inirig_mat                          ../starter/source/elements/initia/inirig_mat.F
!||    inisen                              ../starter/source/tools/sensor/inisen.F
!||    inisoldist                          ../starter/source/initial_conditions/inivol/inisoldist.F
!||    init_monvol                         ../starter/source/airbag/init_monvol.F
!||    initia                              ../starter/source/elements/initia/initia.F
!||    initwg                              ../starter/source/spmd/domain_decomposition/initwg.F
!||    initwg_poutre                       ../starter/source/spmd/domain_decomposition/initwg_poutre.F
!||    initwg_quad                         ../starter/source/spmd/domain_decomposition/initwg_quad.F
!||    initwg_ressort                      ../starter/source/spmd/domain_decomposition/initwg_ressort.F
!||    initwg_shell                        ../starter/source/spmd/domain_decomposition/initwg_shell.F
!||    initwg_solid                        ../starter/source/spmd/domain_decomposition/initwg_solid.F
!||    initwg_tri                          ../starter/source/spmd/domain_decomposition/initwg_tri.F
!||    initwg_truss                        ../starter/source/spmd/domain_decomposition/initwg_truss.F
!||    inivoid                             ../starter/source/elements/initia/inivoid.F
!||    insert_clause_in_set                ../starter/source/model/sets/insert_clause_in_set.F
!||    insol25                             ../starter/source/interfaces/inter3d1/i25buc_vox1.F
!||    insol3                              ../starter/source/interfaces/inter3d1/insol3.F
!||    insol3d                             ../starter/source/interfaces/inter3d1/insol3.F
!||    insol3et                            ../starter/source/interfaces/inter3d1/i24sti3.F
!||    insolbox                            ../starter/source/interfaces/inter3d1/i24sti3.F
!||    insolt10                            ../starter/source/interfaces/inter3d1/insolt10.F
!||    int18_law151_init                   ../engine/source/interfaces/int18/int18_law151_init.F
!||    iwcontdd_151                        ../starter/source/spmd/domain_decomposition/grid2mat.F
!||    lce16q3                             ../starter/source/elements/solid_2d/quad/lce16q.F
!||    lce16s3                             ../starter/source/elements/reader/hm_read_solid.F
!||    lce16s4                             ../starter/source/elements/reader/hm_read_solid.F
!||    lec_inistate                        ../starter/source/elements/initia/lec_inistate.F
!||    lec_inistate_d00_brick_check        ../starter/source/elements/initia/lec_inistate_d00_brick-check.F
!||    lec_inistate_tri                    ../starter/source/elements/initia/lec_inistate_tri.F
!||    lecacc                              ../starter/source/tools/accele/lecacc.F
!||    lecfill                             ../starter/source/elements/initia/lecfill.F
!||    lecgroup                            ../starter/source/groups/lecgroup.F
!||    lecins                              ../starter/source/interfaces/interf1/lecins.F
!||    lecint                              ../starter/source/interfaces/interf1/lecint.F
!||    lecrefsta                           ../starter/source/loads/reference_state/refsta/lecrefsta.F
!||    lecsec42                            ../starter/source/tools/sect/hm_read_sect.F
!||    lecsec4bolt                         ../starter/source/tools/sect/lecsec4bolt.F
!||    lectur                              ../engine/source/input/lectur.F
!||    line_buffer                         ../starter/source/model/sets/line_buffer.F
!||    lslocal                             ../starter/source/elements/xfem/lslocal.F
!||    m24in3                              ../starter/source/materials/mat/mat024/m24in3.F
!||    merge_node                          ../starter/source/elements/nodes/merge_node.F
!||    monvol_check_venthole_surf          ../starter/share/modules1/monvol_struct_mod.F
!||    monvol_compute_volume               ../starter/share/modules1/monvol_struct_mod.F
!||    monvol_orient_surf                  ../starter/share/modules1/monvol_struct_mod.F
!||    monvol_reverse_normals              ../starter/share/modules1/monvol_struct_mod.F
!||    multi_connectivity                  ../starter/source/multifluid/multi_connectivity.F
!||    multi_unplug_neighbors              ../starter/source/multifluid/multi_unplug_neighbors.F
!||    multifluid_init2                    ../starter/source/multifluid/multifluid_init2.F
!||    multifluid_init2t                   ../starter/source/multifluid/multifluid_init2t.F
!||    multifluid_init3                    ../starter/source/multifluid/multifluid_init3.F
!||    multifluid_init3t                   ../starter/source/multifluid/multifluid_init3t.F
!||    nbadmesh                            ../starter/source/model/remesh/nbadmesh.F
!||    new_seatbelt                        ../starter/source/tools/seatbelts/new_seatbelt.F
!||    nloc_dmg_init                       ../starter/source/materials/fail/nloc_dmg_init.F
!||    nlocal_init_sta                     ../starter/source/materials/fail/nlocal_init_sta.F
!||    nodm11                              ../starter/source/materials/mat/mat011/nodm11.F
!||    origin                              ../starter/source/model/remesh/build_admesh.F
!||    outri                               ../starter/source/materials/time_step/outri.F
!||    paroi                               ../starter/source/materials/mat/mat006/paroi.F
!||    parsor                              ../starter/source/output/anim/parsor.F
!||    parsorc                             ../engine/source/output/anim/generate/parsorc.F
!||    parsorf                             ../engine/source/output/anim/generate/parsorf.F
!||    parsors                             ../engine/source/output/anim/generate/parsors.F
!||    pcoori                              ../starter/source/elements/beam/pcoori.F
!||    phase_detection                     ../starter/source/initial_conditions/inivol/phase_detection.F
!||    pinit3                              ../starter/source/elements/beam/pinit3.F
!||    pornod                              ../starter/source/ale/pornod.F
!||    pre_stackgroup                      ../starter/source/stack/pres_stackgroup.F
!||    precrkxfem                          ../starter/source/elements/xfem/precrkxfem.F
!||    preinicrk3n                         ../starter/source/elements/xfem/preinicrk3N.F
!||    preinicrk4n                         ../starter/source/elements/xfem/preinicrk4N.F
!||    preplyxfem                          ../starter/source/properties/composite_options/stack/preplyxfem.F
!||    printgroup                          ../starter/source/output/outfile/printgroup.F
!||    q4init2                             ../starter/source/elements/solid_2d/quad4/q4init2.F
!||    q4rcoor2                            ../engine/source/elements/solid_2d/quad4/q4rcoor2.F
!||    q4voli2                             ../starter/source/elements/solid_2d/quad4/q4voli2.F
!||    qcoor2                              ../engine/source/elements/solid_2d/quad/qcoor2.F
!||    qgrtails                            ../starter/source/elements/solid_2d/quad/qgrtails.F
!||    qinit2                              ../starter/source/elements/solid_2d/quad/qinit2.F
!||    qrcoor2                             ../engine/source/elements/solid_2d/quad/qrcoor2.F
!||    qsurftag                            ../starter/source/groups/qsurftag.F
!||    quad_surface_buffer                 ../starter/source/model/sets/quad_surface_buffer.F
!||    qvoli2                              ../starter/source/elements/solid_2d/quad/qvoli2.F
!||    r1buf3                              ../starter/source/elements/spring/r1buf3.F
!||    r23mass                             ../starter/source/elements/spring/rmass.F
!||    r2buf3                              ../starter/source/elements/spring/r2buf3.F
!||    r2r_check_seg                       ../starter/source/coupling/rad2rad/routines_r2r.F
!||    r2r_group                           ../starter/source/coupling/rad2rad/r2r_group.F
!||    r2r_prelec                          ../starter/source/coupling/rad2rad/r2r_prelec.F
!||    r2r_split                           ../starter/source/coupling/rad2rad/r2r_split.F
!||    r3buf3                              ../starter/source/elements/spring/r3buf3.F
!||    r4buf3                              ../starter/source/elements/spring/r4buf3.F
!||    r4ini                               ../starter/source/elements/spring/rinit3.F
!||    r8ini                               ../starter/source/elements/spring/rinit3.F
!||    ratio_fill                          ../starter/source/initial_conditions/inivol/ratio_fill.F
!||    rcheckmass                          ../starter/source/elements/spring/rcheckmass.F
!||    read_impdisp_fgeo                   ../starter/source/constraints/general/impvel/read_impdisp_fgeo.F
!||    read_impvel_fgeo                    ../starter/source/constraints/general/impvel/read_impvel_fgeo.F
!||    read_impvel_lagmul                  ../starter/source/constraints/general/impvel/read_impvel_lagmul.F
!||    read_monvol                         ../starter/source/airbag/read_monvol.F
!||    read_rwall                          ../starter/source/constraints/general/rwall/read_rwall.F
!||    reconnect                           ../starter/source/elements/nodes/reconnect.F
!||    reini_matprop                       ../starter/source/spmd/domain_decomposition/grid2mat.F
!||    remn_self24                         ../starter/source/interfaces/inter3d1/remn_self24.F
!||    rgrhead                             ../starter/source/elements/spring/rgrhead.F
!||    rgrtails                            ../starter/source/elements/spring/rgrtails.F
!||    rini1u                              ../starter/source/elements/spring/rinit3.F
!||    rini2u                              ../starter/source/elements/spring/rinit3.F
!||    rini33_rb                           ../starter/source/elements/joint/rjoint/rini33_rb.F
!||    rini3u                              ../starter/source/elements/spring/rinit3.F
!||    rini45                              ../starter/source/elements/joint/rjoint/rini45.F
!||    rini45_rb                           ../starter/source/elements/joint/rjoint/rini45_rb.F
!||    rinit3                              ../starter/source/elements/spring/rinit3.F
!||    rmas12                              ../starter/source/elements/spring/rmas12.F
!||    rmass                               ../starter/source/elements/spring/rmass.F
!||    s10coor3                            ../engine/source/elements/solid/solide10/s10coor3.F
!||    s10coor3_old                        ../starter/source/elements/solid/solide10/s10coor3.F
!||    s10init3                            ../starter/source/elements/solid/solide10/s10init3.F
!||    s16coor3                            ../starter/source/elements/thickshell/solide16/s16coor3.F
!||    s16init3                            ../starter/source/elements/thickshell/solide16/s16init3.F
!||    s20coor3                            ../engine/source/elements/solid/solide20/s20coor3.F
!||    s20init3                            ../starter/source/elements/solid/solide20/s20init3.F
!||    s4coor3                             ../engine/source/elements/solid/solide4/s4coor3.F
!||    s4init3                             ../starter/source/elements/solid/solide4/s4init3.F
!||    s4refsta3                           ../starter/source/elements/solid/solide4/s4refsta3.F
!||    s6ccoor3                            ../starter/source/elements/thickshell/solide6c/s6ccoor3.F
!||    s6cinit3                            ../starter/source/elements/thickshell/solide6c/s6cinit3.F
!||    s8cinit3                            ../starter/source/elements/thickshell/solide8c/s8cinit3.F
!||    s8zinit3                            ../starter/source/elements/solid/solide8z/s8zinit3.F
!||    sboxboxsurf                         ../starter/source/model/box/bigbox.F
!||    scaleini                            ../starter/source/elements/initia/scaleini.F
!||    sccoor3                             ../starter/source/elements/thickshell/solidec/sccoor3.F
!||    scinit3                             ../starter/source/elements/thickshell/solidec/scinit3.F
!||    scmorth3                            ../starter/source/elements/thickshell/solidec/scmorth3.F
!||    scoor3                              ../engine/source/elements/solid/solide/scoor3.F
!||    secstri                             ../starter/source/tools/sect/hm_read_sect.F
!||    sectarea                            ../starter/source/loads/bolt/sectarea.F
!||    seteloff                            ../starter/source/constraints/general/rbody/hm_read_rbody.F
!||    seteloff2                           ../starter/source/constraints/general/rbe2/hm_read_rbe2.F
!||    setrb2on                            ../starter/source/constraints/general/rbe2/hm_read_rbe2.F
!||    setrbyon                            ../starter/source/constraints/general/rbody/hm_read_rbody.F
!||    sgrhead                             ../starter/source/elements/solid/solide/sgrhead.F
!||    sgrtails                            ../starter/source/elements/solid/solide/sgrtails.F
!||    sgsavini                            ../starter/source/elements/solid/solide/scoor3.F
!||    sgsavinierefq                       ../starter/source/elements/initia/initia.F
!||    shellthk_upd                        ../starter/source/properties/composite_options/drape/shellthk_upd.F
!||    sinit3                              ../starter/source/elements/solid/solide/sinit3.F
!||    smorth3                             ../starter/source/elements/solid/solide/smorth3.F
!||    sms_auto_dt                         ../starter/source/ams/sms_auto_dt.F
!||    sms_ini_jad_1                       ../engine/source/ams/sms_init.F
!||    sms_ini_jad_2                       ../engine/source/ams/sms_init.F
!||    sms_ini_jad_3                       ../engine/source/ams/sms_init.F
!||    sms_ini_kad                         ../engine/source/ams/sms_init.F
!||    sms_ini_kdi                         ../engine/source/ams/sms_init.F
!||    sms_init                            ../starter/source/ams/sms_init.F
!||    solid_surface_buffer                ../starter/source/model/sets/solid_surface_buffer.F
!||    soltosphv4                          ../starter/source/elements/sph/soltosph.F
!||    soltosphv8                          ../starter/source/elements/sph/soltosph.F
!||    soltosphx4                          ../starter/source/elements/sph/soltosph.F
!||    soltosphx8                          ../starter/source/elements/sph/soltosph.F
!||    sort_surf                           ../starter/source/groups/sort_surf.F
!||    sortgroup                           ../starter/source/system/nintrr.F
!||    spcoor3                             ../starter/source/elements/solid/sconnect/spcoor3.F
!||    split_cfd_solide                    ../starter/source/spmd/split_cfd_solide.F
!||    spmd_anim_ply_init                  ../engine/source/mpi/anim/spmd_anim_ply_init.F
!||    spmd_msin                           ../starter/source/elements/initia/spmd_msin.F
!||    spmd_msin_addmass                   ../starter/source/elements/initia/spmd_msin_addmass.F
!||    spmd_partsav_pon                    ../starter/source/elements/initia/spmd_msin_addmass.F
!||    srcoor3                             ../engine/source/elements/solid/solide/srcoor3.F
!||    srefsta3                            ../starter/source/elements/solid/solide/srefsta3.F
!||    srota6                              ../engine/source/output/anim/generate/srota6.F
!||    srota6_m1                           ../starter/source/output/anim/srota6_M1.F
!||    ssurftag                            ../starter/source/groups/ssurftag.F
!||    st_qaprint_admesh                   ../starter/source/output/qaprint/st_qaprint_admesh.F
!||    st_qaprint_driver                   ../starter/source/output/qaprint/st_qaprint_driver.F
!||    st_qaprint_element                  ../starter/source/output/qaprint/st_qaprint_element.F
!||    st_qaprint_madymo                   ../starter/source/output/qaprint/st_qaprint_madymo.F
!||    st_qaprint_reference_state          ../starter/source/output/qaprint/st_qaprint_reference_state.F
!||    st_qaprint_refsta                   ../starter/source/output/qaprint/st_qaprint_refsta.F
!||    st_qaprint_set                      ../starter/source/output/qaprint/st_qaprint_set.F
!||    stackgroup                          ../starter/source/stack/stackgroup.F
!||    stackgroup_drape                    ../starter/source/stack/stackgroup_drape.F
!||    state_admesh                        ../starter/source/model/remesh/state_admesh.F
!||    suinit3                             ../starter/source/elements/elbuf_init/suinit3.F
!||    surface_buffer                      ../starter/source/model/sets/surface_buffer.F
!||    surfext_tagn                        ../starter/source/groups/ssurftag.F
!||    t3grhead                            ../starter/source/elements/solid_2d/tria/t3grhead.F
!||    t3grtails                           ../starter/source/elements/solid_2d/tria/t3grtails.F
!||    tag_elem_void_r2r                   ../starter/source/coupling/rad2rad/tagelem_r2r.F
!||    tag_elem_void_r2r_lin               ../starter/source/coupling/rad2rad/tagelem_r2r.F
!||    tag_node_from_solid                 ../starter/source/model/sets/tag_node_from_solid.F
!||    tag_node_from_spring                ../starter/source/model/sets/tag_node_from_spring.F
!||    tagnod_r2r_nl                       ../starter/source/coupling/rad2rad/tagnod_r2r_nl.F
!||    tagnodr                             ../starter/source/groups/tagnodr.F
!||    tagnods                             ../starter/source/groups/tagnod.F
!||    tagnods_r2r                         ../starter/source/coupling/rad2rad/tagnod_r2r.F
!||    tensorc                             ../engine/source/output/anim/generate/tensorc.F
!||    tensors                             ../engine/source/output/anim/generate/tensor6.F
!||    thickvar                            ../engine/source/elements/shell/coque/thickvar.F
!||    thskewc                             ../starter/source/output/th/thskewc.F
!||    tinit3                              ../starter/source/elements/truss/tinit3.F
!||    tmass                               ../starter/source/elements/truss/tmass.F
!||    tsurftag                            ../starter/source/groups/tsurftag.F
!||    w_anim_crk                          ../starter/source/restart/ddsplit/w_anim_crk.F
!||    w_anim_ply                          ../starter/source/restart/ddsplit/w_anim_ply.F
!||    w_front                             ../starter/source/restart/ddsplit/w_front.F
!||    w_ithflux                           ../starter/source/restart/ddsplit/w_ithflux.F
!||    w_pon                               ../starter/source/restart/ddsplit/w_pon.F
!||    w_tabmat_prop                       ../starter/source/restart/ddsplit/w_tabmat_prop.F
!||    wrcomip                             ../starter/source/restart/ddsplit/wrcommp.F
!||    write_nloc_struct                   ../engine/source/output/restart/write_nloc_struct.F
!||    writemesh                           ../starter/source/airbag/writeMesh.F
!||    xfem_crack_init                     ../starter/source/elements/xfem/xfem_crack_init.F
!||    xyz16                               ../engine/source/output/anim/generate/monvol_anim.F90
!||    xyznor16                            ../engine/source/output/anim/generate/monvol_anim.F90
!||====================================================================
      module element_mod
! ----------------------------------------------------------------------------------------------------------------------
        integer, parameter :: nixs = 11 !< first dimension of ixs array (solid element)
        integer, parameter :: nixs10 = 6 !< first dimension of ixs10 array (tetrahedral element)
        integer, parameter :: nixs16 = 8 !< first dimension of ixs16 array (solid 16-node element)
        integer, parameter :: nixs20 = 12 !< first dimension of ixs20 array (solid 20-node element)
        integer, parameter :: nixc = 7 !< first dimension of ixc array (shell element)        
        integer, parameter :: nixt = 5 !< first dimension of ixt array (truss element)
        integer, parameter :: nixq = 7 !< first dimension of ixq array (quad element)
        integer, parameter :: nixp = 6 !< first dimension of ixp array (beam element)
        integer, parameter :: nixr = 6 !< first dimension of ixr array (spring element)
        integer, parameter :: nixtg = 6 !< first dimension of ixtg array (shell 3n / triangle element)
        integer, parameter :: nixur = 6 !< first dimension of ixur array (user element)     
! ----------------------------------------------------------------------------------------------------------------------        
      end module element_mod
