#!/bin/bash
#
# This file should be added to the .git/hooks repository
# 
# To enable this hook, rename this file to "pre-commit".


lof=$(git diff --cached --name-only --diff-filter=ACM)  
echo $lof
for fic in $lof
do
if [[ "$fic" == *".F" ]]; then
        echo $fic
        cp $fic ${fic}.backup
        sed -i "/Copyright>/d" ${fic}
        cat scripts/copyright/f_COPYRIGHT.txt ${fic} > pre_commit.tmp
        mv pre_commit.tmp ${fic}
        rm ${fic}.backup
fi
done
exit 0

