/*Copyright>    OpenRadioss
//Copyright>    Copyright (C) 1986-2025 Altair Engineering Inc.
//Copyright>
//Copyright>    This program is free software: you can redistribute it and/or modify
//Copyright>    it under the terms of the GNU Affero General Public License as published by
//Copyright>    the Free Software Foundation, either version 3 of the License, or
//Copyright>    (at your option) any later version.
//Copyright>
//Copyright>    This program is distributed in the hope that it will be useful,
//Copyright>    but WITHOUT ANY WARRANTY; without even the implied warranty of
//Copyright>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//Copyright>    GNU Affero General Public License for more details.
//Copyright>
//Copyright>    You should have received a copy of the GNU Affero General Public License
//Copyright>    along with this program.  If not, see <https://www.gnu.org/licenses/>.
//Copyright>
//Copyright>
//Copyright>    Commercial Alternative: Altair Radioss Software
//Copyright>
//Copyright>    As an alternative to this open-source version, Altair also offers Altair Radioss
//Copyright>    software under a commercial license.  Contact Altair to discuss further if the
//Copyright>    commercial version may interest you: https://www.altair.com/radioss/.*/


#ifndef SDILSDTORAD_DYNAMATLAWKEYWORDMAP_H
#define SDILSDTORAD_DYNAMATLAWKEYWORDMAP_H

#include<map>
#include<string>

namespace sdiD2R
{
    static std::map<std::string, unsigned short int> dynaMatLawMap = 
    {
        {"*MAT_ELASTIC",1},
        {"*MAT_ELASTIC_FLUID",1},
        {"*MAT_ORTHOTROPIC_ELASTIC",2},
        {"*MAT_ANISOTROPIC_ELASTIC",2},
        {"*MAT_PLASTIC_KINEMATIC",3},
        {"*MAT_ELASTIC_PLASTIC_THERMAL",4},
        {"*MAT_SOIL_AND_FOAM",5},
        {"*MAT_VISCOELASTIC",6},
        {"*MAT_BLATZ-KO_RUBBER",7},
        {"*MAT_HIGH_EXPLOSIVE_BURN",8},
        {"*MAT_NULL",9},
        {"*MAT_ELASTIC_PLASTIC_HYDRO",10},
        {"*MAT_STEINBERG",11},
        {"*MAT_STEINBERG_LUND",11},
        {"*MAT_ISOTROPIC_ELASTIC_PLASTIC",12},
        {"*MAT_ISOTROPIC_ELASTIC_FAILURE",13},
        {"*MAT_SOIL_AND_FOAM_FAILURE",14},
        {"*MAT_JOHNSON_COOK",15},
        {"*MAT_PSEUDO_TENSOR",16},
        {"*MAT_ORIENTED_CRACK",17},
        {"*MAT_POWER_LAW_PLASTICITY",18},
        {"*MAT_STRAIN_RATE_DEPENDENT_PLASTICITY",19},
        {"*MAT_RIGID",20},
        {"*MAT_ORTHOTROPIC_THERMAL",21},
        {"*MAT_COMPOSITE_DAMAGE",22},
        {"*MAT_TEMPERATURE_DEPENDENT_ORTHOTROPIC",23},
        {"*MAT_PIECEWISE_LINEAR_PLASTICITY",24},
        {"*MAT_PIECEWISE_LINEAR_PLASTICITY_LOG_INTERPOLATION",24},
        {"*MAT_GEOLOGIC_CAP_MODEL",25},
        {"*MAT_HONEYCOMB",26},
        {"*MAT_MOONEY-RIVLIN_RUBBER",27},
        {"*MAT_RESULTANT_PLASTICITY",28},
        {"*MAT_FORCE_LIMITED",29},
        {"*MAT_SHAPE_MEMORY",30},
        {"*MAT_FRAZER_NASH_RUBBER_MODEL",31},
        {"*MAT_LAMINATED_GLASS",32},
        {"*MAT_BARLAT_ANISOTROPIC_PLASTICITY",33},
        {"*MAT_BARLAT_YLD96",3301},
        {"*MAT_FABRIC",34},
        {"*MAT_FABRIC_MAP",3401},
        {"*MAT_PLASTIC_GREEN-NAGHDI_RATE",35},
        {"*MAT_3-PARAMETER_BARLAT",36},
        {"*MAT_EXTENDED_3-PARAMETER_BARLAT",3601},
        {"*MAT_TRANSVERSELY_ANISOTROPIC_ELASTIC_PLASTIC",37},
        {"*MAT_BLATZ-KO_FOAM",38},
        {"*MAT_FLD_TRANSVERSELY_ANISOTROPIC",39},
        {"*MAT_NONLINEAR_ORTHOTROPIC",40},
        {"*MAT_USER_DEFINED_MATERIAL_MODELS",41},
        {"*MAT_BAMMAN",51},
        {"*MAT_BAMMAN_DAMAGE",52},
        {"*MAT_CLOSED_CELL_FOAM",53},
        {"*MAT_ENHANCED_COMPOSITE_DAMAGE",54},
        {"*MAT_LOW_DENSITY_FOAM",57},
        {"*MAT_LAMINATED_COMPOSITE_FABRIC",58},
        {"*MAT_LAMINATED_COMPOSITE_FABRIC_SOLID",58},
        {"*MAT_COMPOSITE_FAILURE",59},
        {"*MAT_ELASTIC_WITH_VISCOSITY",60},
        {"*MAT_KELVIN-MAXWELL_VISCOELASTIC",61},
        {"*MAT_VISCOUS_FOAM",62},
        {"*MAT_CRUSHABLE_FOAM",63},
        {"*MAT_RATE_SENSITIVE_POWERLAW_PLASTICITY",64},
        {"*MAT_MODIFIED_ZERILLI_ARMSTRONG",65},
        {"*MAT_LINEAR_ELASTIC_DISCRETE_BEAM",66},
        {"*MAT_NONLINEAR_ELASTIC_DISCRETE_BEAM",67},
        {"*MAT_NONLINEAR_PLASTIC_DISCRETE_BEAM",68},
        {"*MAT_SID_DAMPER_DISCRETE_BEAM",69},
        {"*MAT_HYDRAULIC_GAS_DAMPER_DISCRETE_BEAM",70},
        {"*MAT_CABLE_DISCRETE_BEAM",71},
        {"*MAT_CONCRETE_DAMAGE",72},
        {"*MAT_CONCRETE_DAMAGE_REL3",72},
        {"*MAT_LOW_DENSITY_VISCOUS_FOAM",73},
        {"*MAT_ELASTIC_SPRING_DISCRETE_BEAM",74},
        {"*MAT_BILKHU_DUBOIS_FOAM",75},
        {"*MAT_GENERAL_VISCOELASTIC",76},
        {"*MAT_HYPERELASTIC_RUBBER",77},
        {"*MAT_OGDEN_RUBBER",7701},
        {"*MAT_SOIL_CONCRETE",78},
        {"*MAT_HYSTERETIC_SOIL",79},
        {"*MAT_RAMBERG-OSGOOD",80},
        {"*MAT_PLASTICITY_WITH_DAMAGE",81},
        {"*MAT_FU_CHANG_FOAM",83},
        {"*MAT_WINFRITH_CONCRETE",84},
        {"*MAT_ORTHOTROPIC_VISCOELASTIC",86},
        {"*MAT_CELLULAR_RUBBER",87},
        {"*MAT_MTS",88},
        {"*MAT_PLASTICITY_POLYMER",89},
        {"*MAT_ACOUSTIC",90},
        {"*MAT_SOFT_TISSUE",91},
        {"*MAT_SOFT_TISSUE_VISCO",91},
        {"*MAT_ELASTIC_6DOF_SPRING_DISCRETE_BEAM",93},
        {"*MAT_INELASTIC_SPRING_DISCRETE_BEAM",94},
        {"*MAT_INELASTIC_6DOF_SPRING_DISCRETE_BEAM",95},
        {"*MAT_BRITTLE_DAMAGE",96},
        {"*MAT_GENERAL_JOINT_DISCRETE_BEAM",97},
        {"*MAT_SIMPLIFIED_JOHNSON_COOK",98},
        {"*MAT_SIMPLIFIED_JOHNSON_COOK_ORTHOTROPIC_DAMAGE",99},
        {"*MAT_SPOTWELD",100},
        {"*MAT_SPOTWELD_DAMAGE-FAILURE",100},
        {"*MAT_GEPLASTIC_SRATE_2000a",101},
        {"*MAT_INV_HYPERBOLIC_SIN",102},
        {"*MAT_ANISOTROPIC_VISCOPLASTIC",103},
        {"*MAT_ANISOTROPIC_PLASTIC",10301},
        {"*MAT_DAMAGE_1",104},
        {"*MAT_DAMAGE_2",105},
        {"*MAT_ELASTIC_VISCOPLASTIC_THERMAL",106},
        {"*MAT_MODIFIED_JOHNSON_COOK",107},
        {"*MAT_ORTHO_ELASTIC_PLASTIC",108},
        {"*MAT_JOHNSON_HOLMQUIST_CERAMICS",110},
        {"*MAT_JOHNSON_HOLMQUIST_CONCRETE",111},
        {"*MAT_FINITE_ELASTIC_STRAIN_PLASTICITY",112},
        {"*MAT_TRIP",113},
        {"*MAT_LAYERED_LINEAR_PLASTICITY",114},
        {"*MAT_UNIFIED_CREEP",115},
        {"*MAT_UNIFIED_CREEP_ORTHO",115},
        {"*MAT_COMPOSITE_LAYUP",116},
        {"*MAT_COMPOSITE_MATRIX",117},
        {"*MAT_COMPOSITE_DIRECT",118},
        {"*MAT_GENERAL_NONLINEAR_6DOF_DISCRETE_BEAM",119},
        {"*MAT_GURSON",120},
        {"*MAT_GENERAL_NONLINEAR_1DOF_DISCRETE_BEAM",121},
        {"*MAT_HILL_3R",122},
        {"*MAT_MODIFIED_PIECEWISE_LINEAR_PLASTICITY",123},
        {"*MAT_PLASTICITY_COMPRESSION_TENSION",124},
        {"*MAT_KINEMATIC_HARDENING_TRANSVERSELY_ANISOTROPIC",125},
        {"*MAT_MODIFIED_HONEYCOMB",126},
        {"*MAT_ARRUDA_BOYCE_RUBBER",127},
        {"*MAT_HEART_TISSUE",128},
        {"*MAT_LUNG_TISSUE",129},
        {"*MAT_SPECIAL_ORTHOTROPIC",130},
        {"*MAT_ISOTROPIC_SMEARED_CRACK",131},
        {"*MAT_ORTHOTROPIC_SMEARED_CRACK",132},
        {"*MAT_BARLAT_YLD2000",133},
        {"*MAT_VISCOELASTIC_FABRIC",134},
        {"*MAT_WTM_STM",135},
        {"*MAT_CORUS_VEGTER",136},
        {"*MAT_COHESIVE_MIXED_MODE",138},
        {"*MAT_MODIFIED_FORCE_LIMITED",139},
        {"*MAT_VACUUM",140},
        {"*MAT_RATE_SENSITIVE_POLYMER",141},
        {"*MAT_TRANSVERSELY_ISOTROPIC_CRUSHABLE_FOAM",142},
        {"*MAT_WOOD",143},
        {"*MAT_PITZER_CRUSHABLE_FOAM",144},
        {"*MAT_SCHWER_MURRAY_CAP_MODEL",145},
        {"*MAT_1DOF_GENERALIZED_SPRING",146},
        {"*MAT_FHWA_SOIL",147},
        {"*MAT_GAS_MIXTURE",148},
        {"*MAT_EMMI",151},
        {"*MAT_DAMAGE3",153},
        {"*MAT_DESHPANDE_FLECK_FOAM",154},
        {"*MAT_PLASTICITY_COMPRESSION_TENSION_EOS",155},
        {"*MAT_MUSCLE",156},
        {"*MAT_ANISOTROPIC_ELASTIC_PLASTIC",157},
        {"*MAT_RATE_SENSITIVE_COMPOSITE_FABRIC",158},
        {"*MAT_CSCM",159},
        {"*MAT_ALE_INCOMPRESSIBLE",160},
        {"*MAT_COMPOSITE_MSC",161},
        {"*MAT_MODIFIED_CRUSHABLE_FOAM",163},
        {"*MAT_BRAIN_LINEAR_VISCOELASTIC",164},
        {"*MAT_PLASTIC_NONLINEAR_KINEMATIC",165},
        {"*MAT_MOMENT_CURVATURE_BEAM",166},
        {"*MAT_MCCORMICK",167},
        {"*MAT_POLYMER",168},
        {"*MAT_ARUP_ADHESIVE",169},
        {"*MAT_RESULTANT_ANISOTROPIC",170},
        {"*MAT_STEEL_CONCENTRIC_BRACE",171},
        {"*MAT_CONCRETE_EC2",172},
        {"*MAT_MOHR_COULOMB",173},
        {"*MAT_RC_BEAM",174},
        {"*MAT_VISCOELASTIC_THERMAL",175},
        {"*MAT_QUASILINEAR_VISCOELASTIC",176},
        {"*MAT_HILL_FOAM",177},
        {"*MAT_VISCOELASTIC_HILL_FOAM",178},
        {"*MAT_LOW_DENSITYSYNTHETIC_FOAM",179},
        {"*MAT_SIMPLIFIED_RUBBER/FOAM",181},
        {"*MAT_SIMPLIFIED_RUBBER",181},
        {"*MAT_SIMPLIFIED_RUBBER_WITH_DAMAGE",183},
        {"*MAT_COHESIVE_ELASTIC",184},
        {"*MAT_COHESIVE_TH",185},
        {"*MAT_COHESIVE_GENERAL",186},
        {"*MAT_SAMP-1",187},
        {"*MAT_THERMO_ELASTO_VISCOPLASTIC_CREEP",188},
        {"*MAT_ANISOTROPIC_THERMOELASTIC",189},
        {"*MAT_FLD3-PARAMETER_BARLAT",190},
        {"*MAT_SEISMIC_BEAM",191},
        {"*MAT_SOIL_BRICK",192},
        {"*MAT_DRUCKER_PRAGER",193},
        {"*MAT_RC_SHEAR_WALL",194},
        {"*MAT_CONCRETE_BEAM",195},
        {"*MAT_GENERAL_SPRING_DISCRETE_BEAM",196},
        {"*MAT_SEISMIC_ISOLATOR",197},
        {"*MAT_JOINTED_ROCK",198},
        {"*MAT_STEEL_EC3",202},
        {"*MAT_HYSTERETIC_REINFORCEMENT",203},
        {"*MAT_BOLT_BEAM",208},
        {"*MAT_SPR_JLR",211},
        {"*MAT_DRY_FABRIC",214},
        {"*MAT_4A_MICROMEC",215},
        {"*MAT_ELASTIC_PHASE_CHANGE",216},
        {"*MAT_OPTIONTROPIC_ELASTIC_PHASE_CHANGE",217},
        {"*MAT_MOONEY-RIVLIN_PHASE_CHANGE",218},
        {"*MAT_CODAM2",219},
        {"*MAT_RIGID_DISCRETE",220},
        {"*MAT_ORTHOTROPIC_SIMPLIFIED_DAMAGE",221},
        {"*MAT_TABULATED_JOHNSON_COOK",224},
        {"*MAT_TABULATED_JOHNSON_COOK_LOG_INTERPOLATION",224},
        {"*MAT_VISCOPLASTIC_MIXED_HARDENING",225},
        {"*MAT_KINEMATIC_HARDENING_BARLAT89",226},
        {"*MAT_PML_ELASTIC",230},
        {"*MAT_PML_ACOUSTIC",231},
        {"*MAT_BIOT_HYSTERETIC",232},
        {"*MAT_CAZACU_BARLAT",233},
        {"*MAT_VISCOELASTIC_LOOSE_FABRIC",234},
        {"*MAT_MICROMECHANICS_DRY_FABRIC",235},
        {"*MAT_SCC_ON_RCC",236},
        {"*MAT_PML_HYSTERETIC",237},
        {"*MAT_PERT_PIECEWISE_LINEAR_PLASTICITY",238},
        {"*MAT_COHESIVE_MIXED_MODE_ELASTOPLASTIC_RATE",240},
        {"*MAT_JOHNSON_HOLMQUIST_JH1",241},
        {"*MAT_KINEMATIC_HARDENING_BARLAT2000",242},
        {"*MAT_HILL_90",243},
        {"*MAT_UHSSTEEL",244},
        {"*MAT_PML_OPTIONTROPIC_ELASTIC",245},
        {"*MAT_PML_NULL",246},
        {"*MAT_PHS_BMW",248},
        {"*MAT_REINFORCED_THERMOPLASTIC",249},
        {"*MAT_TAILORED_PROPERTIES",251},
        {"*MAT_TOUGHENED_ADHESIVE_POLYMER",252},
        {"*MAT_GENERALIZED_PHASE_CHANGE",254},
        {"*MAT_PIECEWISE_LINEAR_PLASTIC_THERMAL",255},
        {"*MAT_AMORPHOUS_SOLIDS_FINITE_STRAIN",256},
        {"*MAT_STOUGHTON_NON_ASSOCIATED_FLOW",260},
        {"*MAT_MOHR_NON_ASSOCIATED_FLOW",26001},
        {"*MAT_LAMINATED_FRACTURE_DAIMLER_PINHO",261},
        {"*MAT_LAMINATED_FRACTURE_DAIMLER_CAMANHO",262},
        {"*MAT_TABULATED_JOHNSON_COOK_ORTHO_PLASTICITY",264},
        {"*MAT_TISSUE_DISPERSED",266},
        {"*MAT_EIGHT_CHAIN_RUBBER",267},
        {"*MAT_BERGSTROM_BOYCE_RUBBER",269},
        {"*MAT_CWM",270},
        {"*MAT_POWDER",271},
        {"*MAT_RHT",272},
        {"*MAT_CDPM",273},
        {"*MAT_CONCRETE_DAMAGE_PLASTIC_MODEL",273},
        {"*MAT_PAPER",274},
        {"*MAT_SMOOTH_VISCOELASTIC_VISCOPLASTIC",275},
        {"*MAT_CHRONOLOGICAL_VISCOELASTIC",276},
        {"*MAT_ADHESIVE_CURING_VISCOELASTIC",277},
        {"*MAT_CF_MICROMECHANICS",278},
        {"*MAT_COHESIVE_PAPER",279},
        {"*MAT_GLASS",280},
        {"*MAT_COMPRF",293},
        {"*MAT_ANAND_VISCOPLASTICITY",296},
        {"*MAT_SPRING_ELASTIC",501},
        {"*MAT_DAMPER_VISCOUS",502},
        {"*MAT_SPRING_ELASTOPLASTIC",503},
        {"*MAT_SPRING_NONLINEAR_ELASTIC",504},
        {"*MAT_DAMPER_NONLINEAR_VISCOUS",505},
        {"*MAT_SPRING_GENERAL_NONLINEAR",506},
        {"*MAT_SPRING_MAXWELL",507},
        {"*MAT_SPRING_INELASTIC",508},
        {"*MAT_SPRING_TRILINEAR_DEGRADING",513},
        {"*MAT_SPRING_SQUAT_SHEARWALL",514},
        {"*MAT_SPRING_MUSCLE",515},
        {"*MAT_ALE_VACUUM",701 },
        {"*MAT_ALE_GAS_MIXTURE",702 },
        {"*MAT_ALE_VISCOUS",703 },
        {"*MAT_ALE_MIXING_LENGTH",704 },
        {"*MAT_ALE_INCOMPRESSIBLE",705 },
        {"*MAT_ALE_HERSCHEL",706 },
        {"*MAT_SEATBELT",801 },
        {"*MAT_SEATBELT_2D",801 },
        {"*MAT_SPH_VISCOUS",901 },
        {"*MAT_001",1 },
        {"*MAT_002",2 },
        {"*MAT_003",3 },
        {"*MAT_006",6 },
        {"*MAT_007",7 },
        {"*MAT_009",9 },
        {"*MAT_012",12 },
        {"*MAT_015",15 },
        {"*MAT_018",18 },
        {"*MAT_019",19 },
        {"*MAT_020",20 },
        {"*MAT_024",24 },
        {"*MAT_026",26 },
        {"*MAT_027",27 },
        {"*MAT_032",32 },
        {"*MAT_034",34 },
        {"*MAT_054",54 },
        {"*MAT_057",57 },
        {"*MAT_058",58 },
        {"*MAT_061",61 },
        {"*MAT_066",66 },
        {"*MAT_067",67 },
        {"*MAT_068",68 },
        {"*MAT_071",71 },
        {"*MAT_074",74 },
        {"*MAT_077_H",77 },
        {"*MAT_077_O",7701 },
        {"*MAT_081",81 },
        {"*MAT_083",83 },
        {"*MAT_091",91 },
        {"*MAT_092",91 },
        {"*MAT_097",97 },
        {"*MAT_098",98 },
        {"*MAT_099",99 },
        {"*MAT_100",100 },
        {"*MAT_105",105 },
        {"*MAT_119",119 },
        {"*MAT_120",120 },
        {"*MAT_121",121 },
        {"*MAT_122",122},
        {"*MAT_123",123 },
        {"*MAT_126",126 },
        {"*MAT_169",169 },
        {"*MAT_181",181 },
        {"*MAT_224",224 },
        {"*MAT_240",240 },
        {"*MAT_S01",501 },
        {"*MAT_S02",502 },
        {"*MAT_S03",503 },
        {"*MAT_S04",504 },
        {"*MAT_S05",505 },
        {"*MAT_S06",506 },
        {"*MAT_S07",507 },
        {"*MAT_S08",508 },
        {"*MAT_S15",515 },
        {"*MAT_B01",801 },
        {"*MAT_B01_2D",801 },
    };
    static std::map<std::string, unsigned short int> dynaEosMap = 
    {
        {"*EOS_LINEAR_POLYNOMIAL",1 },
        {"*EOS_GRUNEISEN",4 },
    };
}

#endif //SDILSDTORAD_DYNAMATLAWKEYWORDMAP_H

