# CPP Compiler Flags
# ------------------
set (PRECOM_DEFINITION "-DNO_DECLS -DBOOST_ALL_NO_LIB -DNDEBUG -D_SECURE_SCL=0 -DWIN32 -DOS_WIN -D_MBCS -DHAVE_SNPRINTF -D_ENABLE_ATOMIC_ALIGNMENT_FIX -D_WIN64  -DNO_GZ_LIB -DTXT_MSG -DUNV -DHC_DATA_DLL_EXPORTS -D_64BITS -D_VC80_UPGRADE=0x0600  -D_CFLAG -D_CONSOLE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_LIB -D_WINDOWS -D_WS__ -D_WS_WIN32_ -DUSE_NAMESPACE -D_WIN32" )
set (CXX_FLAGS "-nologo -O2 -Ob1 -GF -Gy -std:c++14 -Zc:__cplusplus -guard:cf -MT -O2 -GS- -W3 -w34906 -w34265 -w34928 -w34431 -GR -EHsc -FC -FS -wd4996 -TP" )

# C Compiler Flags
# --------------
set (C_PRECOM_DEFINITION " -DNO_GZ_LIB -DTXT_MSG -DUNV -DHC_DATA_DLL_EXPORTS -D_64BITS -D_VC80_UPGRADE=0x0600  -D_CFLAG -D_CONSOLE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_LIB -D_MBCS -D_VC80_UPGRADE=0x0600 -D_WINDOWS -D_WS__ -D_WS_WIN32_ -DUSE_NAMESPACE -D_WIN32  -DBOOST_ALL_NO_LIB -DNDEBUG -DWIN32 -DOS_WIN -D_MBCS -D_WIN64 -DHC_DATA_DLL_EXPORT" )
set (C_FLAGS "-nologo  -O2 -Ob1 -GF -Gy -MT -O2 -GS- -FC -FS -wd4996 -TC  " )
