## MPI setup for NVIDIA HPC SDK — uses HPC-X OpenMPI bundled with the SDK.
## Sets: mpi_suf, mpi_flag, mpi_inc, mpi_lib
## Reads: MPI, mpi_os, mpi_root, mpi_incdir, mpi_libdir, NVHPC (env)
if (DEFINED MPI)
  set(mpiver "${MPI}")
  if (mpiver STREQUAL "smp")
    set(mpi_suf "")
  elseif (mpiver STREQUAL "ompi")
    set(nvhpcx_root "/opt/nvidia/hpc_sdk/Linux_x86_64/26.3/comm_libs/13.1/hpcx/hpcx-2.25.1/ompi")
    if (DEFINED ENV{NVHPC})
      file(GLOB _hpcx_dirs "$ENV{NVHPC}/comm_libs/*/hpcx/*/ompi")
      list(LENGTH _hpcx_dirs _hpcx_count)
      if (_hpcx_count GREATER 0)
        list(GET _hpcx_dirs -1 nvhpcx_root)
      endif()
    endif()
    set(mpi_inc "-I${nvhpcx_root}/include/")
    set(mpi_lib "-L${nvhpcx_root}/lib -lmpi -lmpi_mpifh")
    if (mpi_os STREQUAL "1")
      set(mpi_inc " ")
      set(mpi_lib "-lmpi -lmpi_mpifh")
    else()
      if (DEFINED mpi_root)
        set(mpi_inc "-I${mpi_root}/include/")
        set(mpi_lib "-L${mpi_root}/lib -lmpi -lmpi_mpifh")
      else()
        if (DEFINED mpi_incdir)
          set(mpi_inc "-I${mpi_incdir}")
        endif()
        if (DEFINED mpi_libdir)
          set(mpi_lib "-L${mpi_libdir} -lmpi -lmpi_mpifh")
        endif()
      endif()
    endif()
    set(mpi_suf "_${mpiver}")
    set(mpi_flag "-DMPI ${mpi_inc}")
  else()
    message(FATAL_ERROR "\n ERROR : -mpi=${mpiver} not available for this platform\n\n")
  endif()
endif()
